### ISSUE TITLE
仅支持太极还是所有的Xposed/类Xposed框架？

### ISSUE THREAD

**Issue by Higanoneko** [notxx/NevolutionXposed#5]
我是EdXposed用户，看到Release里面都加了个太极就很好奇
（个人不建议有Magisk环境下使用太极）

**Comment by xesp** [comment]
root了吗，我都是直接用的，不过是root和lsp，

**Comment by TimeRainStarSky** [comment]
> root了吗，我都是直接用的，不过是root和lsp，

请问LSPosed作用域怎么选？

**Comment by xesp** [comment]
系统和微信就行。

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "notxx/NevolutionXposed"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月18日(星期四) 晚上10:13
收件人:&nbsp;"notxx/NevolutionXposed"<NevolutionXposed@noreply.github.com&gt;;
抄送:&nbsp;"淡淡的U"<d3y@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [notxx/NevolutionXposed] 仅支持太极还是所有的Xposed/类Xposed框架？ (#5)





  
root了吗，我都是直接用的，不过是root和lsp，
  
请问LSPosed作用域怎么选？

**Comment by xesp** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
